# -*- coding: utf-8 -*-
"""สำเนาของ 222มนัสพร.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vleooHb08b34FyV6Gm9MkVzZEC2TUY56
"""

!pip install streamlit

import requests
res = requests.get('https://open.er-api.com/v6/latest/USD').json()
print(res['result'], '| 1 USD =', res['rates']['THB'], 'THB')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import requests
# import streamlit as st
# 
# # เรียก API อัตราแลกเปลี่ยนจาก ExchangeRate-API (ฐาน USD)
# url = "https://open.er-api.com/v6/latest/USD"
# data = requests.get(url).json()
# rates = data["rates"]
# 
# st.title("อัตราแลกเปลี่ยนจาก USD")
# 
# # แสดงค่าเงินบาทเป็นหลัก
# st.header(f"1 USD = {rates['THB']:.2f} THB")
# 
# # ให้เลือกสกุลเงินอื่น (ค่าเริ่มต้น THB)
# currencies = list(rates.keys())
# currency = st.selectbox("เลือกสกุลเงินอื่น", currencies, index=currencies.index("THB"))
# 
# st.write(f"1 USD = {rates[currency]:.2f} {currency}")

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared

!nohup streamlit run app.py --server.port 8501 --server.headless true > streamlit.log 2>&1 &
import time; time.sleep(5)
!tail -n 5 streamlit.log

!./cloudflared tunnel --url http://localhost:8501

